import { useState } from 'react';
import { Link2, Copy, Check, Mail, MessageCircle, Facebook, Twitter } from 'lucide-react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from './ui/dialog';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Label } from './ui/label';
import { Separator } from './ui/separator';
import { toast } from 'sonner@2.0.3';

interface ShareModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  documentName: string;
}

export function ShareModal({ open, onOpenChange, documentName }: ShareModalProps) {
  const [copied, setCopied] = useState(false);
  
  // Generate a shareable link (in a real app, this would be generated by your backend)
  const shareLink = `${window.location.origin}/chat/shared/${generateShareId()}`;

  function generateShareId(): string {
    // Generate a random share ID for demo purposes
    return Math.random().toString(36).substring(2, 15);
  }

  const handleCopyLink = async () => {
    try {
      await navigator.clipboard.writeText(shareLink);
      setCopied(true);
      toast.success('Link copied to clipboard!');
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      toast.error('Failed to copy link');
    }
  };

  const handleShareVia = (platform: string) => {
    const encodedLink = encodeURIComponent(shareLink);
    const encodedText = encodeURIComponent(`Check out this chat about "${documentName}" on DocChat AI`);
    
    let url = '';
    switch (platform) {
      case 'email':
        url = `mailto:?subject=${encodeURIComponent(`Shared: ${documentName}`)}&body=${encodedText}%0A%0A${encodedLink}`;
        break;
      case 'twitter':
        url = `https://twitter.com/intent/tweet?text=${encodedText}&url=${encodedLink}`;
        break;
      case 'facebook':
        url = `https://www.facebook.com/sharer/sharer.php?u=${encodedLink}`;
        break;
      case 'whatsapp':
        url = `https://wa.me/?text=${encodedText}%20${encodedLink}`;
        break;
    }
    
    if (url) {
      window.open(url, '_blank', 'noopener,noreferrer');
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Link2 className="h-5 w-5" />
            Share Chat
          </DialogTitle>
          <DialogDescription>
            Anyone with this link can view your conversation about this document
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-4">
          <div className="space-y-2">
            <Label htmlFor="share-link">Share Link</Label>
            <div className="flex items-center gap-2">
              <Input
                id="share-link"
                value={shareLink}
                readOnly
                className="bg-gray-50"
              />
              <Button
                size="icon"
                variant={copied ? "default" : "outline"}
                onClick={handleCopyLink}
                className="flex-shrink-0"
              >
                {copied ? (
                  <Check className="h-4 w-4" />
                ) : (
                  <Copy className="h-4 w-4" />
                )}
              </Button>
            </div>
            <p className="text-xs text-gray-500">
              This link will expire in 7 days
            </p>
          </div>

          <Separator />

          <div className="space-y-3">
            <Label>Share via</Label>
            <div className="grid grid-cols-2 gap-2">
              <Button
                variant="outline"
                onClick={() => handleShareVia('email')}
                className="justify-start"
              >
                <Mail className="h-4 w-4 mr-2" />
                Email
              </Button>
              <Button
                variant="outline"
                onClick={() => handleShareVia('whatsapp')}
                className="justify-start"
              >
                <MessageCircle className="h-4 w-4 mr-2" />
                WhatsApp
              </Button>
              <Button
                variant="outline"
                onClick={() => handleShareVia('twitter')}
                className="justify-start"
              >
                <Twitter className="h-4 w-4 mr-2" />
                Twitter
              </Button>
              <Button
                variant="outline"
                onClick={() => handleShareVia('facebook')}
                className="justify-start"
              >
                <Facebook className="h-4 w-4 mr-2" />
                Facebook
              </Button>
            </div>
          </div>

          <Separator />

          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
            <h4 className="text-sm text-blue-900 mb-2">Privacy Notice</h4>
            <ul className="space-y-1 text-xs text-blue-800">
              <li className="flex items-start gap-2">
                <div className="h-1.5 w-1.5 bg-blue-600 rounded-full mt-1.5 flex-shrink-0" />
                <span>Recipients can view the conversation and document content</span>
              </li>
              <li className="flex items-start gap-2">
                <div className="h-1.5 w-1.5 bg-blue-600 rounded-full mt-1.5 flex-shrink-0" />
                <span>They cannot edit or add new messages</span>
              </li>
              <li className="flex items-start gap-2">
                <div className="h-1.5 w-1.5 bg-blue-600 rounded-full mt-1.5 flex-shrink-0" />
                <span>You can revoke access anytime from settings</span>
              </li>
            </ul>
          </div>
        </div>

        <div className="flex justify-end gap-2">
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            Close
          </Button>
          <Button onClick={handleCopyLink}>
            {copied ? 'Copied!' : 'Copy Link'}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
